name: Build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - uses: DamianReeves/write-file-action@v1.2
        with:
          path: include/wifi_credentials.h
          contents: |
            #define WIFI_SSID "${{ secrets.WIFI_SSID }}"
            #define WIFI_PASSWORD "${{ secrets.WIFI_PASSWORD }}"
      - run: pip install --upgrade platformio
      - run: pio run
      - run: pio pkg pack lib/RaiseDev
      - uses: actions/upload-artifact@v3
        with:
          name: firmware-${{github.sha}}.bin
          path: .pio/build/esp32dev/firmware.bin
      - uses: raisedevs/firmware-upload-action@main
        id: firmware-upload
        if: github.ref == 'refs/heads/main'
        with:
          name: Raise's ESP32 firmware
          path: .pio/build/esp32dev/firmware.bin
      - name: Output firmware URLs
        if: github.ref == 'refs/heads/main'
        run: |
          echo Firmware URL: ${{ steps.firmware-upload.outputs.url }}
          echo Firmware Binary URL: ${{ steps.firmware-upload.outputs.binary-url }}
